name: Setup Flutter
description: Setup flutter project and toolchains for subsequent actions.

inputs:
  target:
    description: "The working directory where the Flutter project is located."
    required: false
    default: "."
  version:
    description: "The version of Flutter to install."
    required: false
    default: "3.x"

runs:
  using: "composite"
  steps:
    - name: Install Flutter SDK
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version: ${{ inputs.version }}
        cache: true

    - name: Flutter version
      run: flutter --version
      shell: bash

    - name: Install dependencies
      run: flutter pub get
      shell: bash
      working-directory: ${{ inputs.target }}
