name: Setup Flutter
description: Setup flutter project and toolchains for subsequent actions.
runs:
  using: "composite"
  steps:
    - name: Install Flutter SDK
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version: 3.x
        cache: true

    - name: Flutter version
      run: flutter --version

    - name: Install dependencies
      run: flutter pub get
