version: 2
updates:
  # Main package dependencies
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "build(pkg)"
      prefix-development: "chore(pkg)"
    labels: []
    groups:
      dependencies:
        dependency-type: "production"
      dev-dependencies:
        dependency-type: "development"

  # Example project dependencies
  - package-ecosystem: "pub"
    directory: "/example"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "build(example)"
    labels: []
