include: all_lint_rules.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**

formatter:
  trailing_commas: preserve

linter:
  rules:
    always_put_control_body_on_new_line: false
    use_setters_to_change_properties: false
    one_member_abstracts: false
    avoid_redundant_argument_values: false
    require_trailing_commas: false
    prefer_int_literals: false
    flutter_style_todos: false
    cascade_invocations: false
    join_return_with_assignment: false
    always_use_package_imports: false
    prefer_relative_imports: true
    unnecessary_parenthesis: false
    avoid_positional_boolean_parameters: false
    omit_obvious_property_types: false
    public_member_api_docs: false
    prefer_expression_function_bodies: false
    diagnostic_describe_all_properties: false
    prefer_asserts_with_message: false
    always_put_required_named_parameters_first: false
    document_ignores: false
    unsafe_variance: false
