name: "Install git-cliff"
description: "Downloads, extracts, and adds git-cliff to the PATH"
inputs:
  version:
    description: "The git-cliff version to install"
    required: false
    default: "2.8.0"

runs:
  using: "composite"
  steps:
    - name: Download and Extract git-cliff
      shell: bash
      run: |
        VERSION=${{ inputs.version }}
        OS_ARCH="x86_64-unknown-linux-gnu" # Assuming Linux x86_64 for now

        CLIFF_FILENAME="git-cliff-${VERSION}-${OS_ARCH}.tar.gz"
        CLIFF_DIRNAME="git-cliff-${VERSION}-${OS_ARCH}"
        CLIFF_URL="https://github.com/orhun/git-cliff/releases/download/v${VERSION}/${CLIFF_FILENAME}"

        echo "Downloading git-cliff v${VERSION} from ${CLIFF_URL}"
        curl -Ls "${CLIFF_URL}" | tar xz

        echo "Adding $PWD/${CLIFF_DIRNAME}/ to PATH"
        echo "$PWD/${CLIFF_DIRNAME}/" >> $GITHUB_PATH

    - name: Verify git-cliff installation
      shell: bash
      run: |
        git-cliff --version
