#!/usr/bin/env bash
set -euo pipefail

EXCLUDE_PATTERN='^(?!.*(fujidaiti|Daichi Fujita|\[bot\])).*'

echo "<!-- THIS FILE WAS GENERATED BY tool/contrib.sh. DO NOT EDIT MANUALLY. -->"
echo "# Contributors"
echo
echo "Thank you for all contributors!"
echo

git shortlog -n \
  --perl-regexp \
  --author="$EXCLUDE_PATTERN" \
  --format="%s - [%h](https://github.com/fujidaiti/smooth_sheets/commit/%h)" \
  HEAD \
  | awk '
      # A divider between contributors
      /^[ \t]*$/ {
	print ""
        next
      }
      # E.g., "- ContributorName (3):"
      /^[A-Za-z]/ {
        print "- " $0
        next
      }
      # E.g., "  - Commit message"
      {
        gsub(/^[ \t]+/, "")
        print "  - " $0
      }
  '

