name: smooth_sheets
description: Sheet widgets with smooth motion and great flexibility. Also supports nested navigation in both imperative and declarative ways.
version: 0.9.2
repository: https://github.com/fujidaiti/smooth_sheets
screenshots:
  - description: Practical examples of smooth_sheets.
    path: resources/smooth-sheets-thumbnail.png
topics:
  - ui
  - widget
  - bottom-sheet

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  collection: ^1.17.1
  flutter:
    sdk: flutter
  meta: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: ^1.23.0
