name: Publish
on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+*"]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: ./.github/actions/setup_flutter
      
      - name: Setup OIDC token
        uses: dart-lang/setup-dart@v1

      - name: Publish to pub.dev
        run: flutter pub publish --force
